package cpm

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

func GenerateCMake(root string, lock Lock) error {
	byID := map[string]Package{}
	for _, p := range lock.Packages {
		byID[p.ID] = p
	}
	seen, visiting := map[string]bool{}, map[string]bool{}
	var ordered []Package
	var visit func(string) error
	visit = func(id string) error {
		if seen[id] {
			return nil
		}
		if visiting[id] {
			return fmt.Errorf("dependency cycle involving %s", id)
		}
		p, ok := byID[id]
		if !ok {
			return fmt.Errorf("lock references missing package %s", id)
		}
		visiting[id] = true
		deps := append([]string(nil), p.Dependencies...)
		sort.Strings(deps)
		for _, dep := range deps {
			if err := visit(dep); err != nil {
				return err
			}
		}
		visiting[id] = false
		seen[id] = true
		ordered = append(ordered, p)
		return nil
	}
	for _, p := range lock.Packages {
		if err := visit(p.ID); err != nil {
			return err
		}
	}
	var b strings.Builder
	b.WriteString("# Generated by cpm; do not edit.\ninclude_guard(GLOBAL)\nget_filename_component(_CPM_ROOT \"${CMAKE_CURRENT_LIST_DIR}/..\" ABSOLUTE)\n")
	for _, p := range ordered {
		s, err := ParseSource(p.Source)
		if err != nil {
			return err
		}
		relative := filepath.ToSlash(filepath.Join("packages", s.Host, s.Owner, s.Repo, p.Commit))
		if p.BuildSystem == "cmake" {
			fmt.Fprintf(&b, "add_subdirectory(\"${_CPM_ROOT}/%s\" \"${CMAKE_BINARY_DIR}/.cpm/%s\" EXCLUDE_FROM_ALL)\n", relative, safePath(p.ID))
		} else if p.BuildSystem == "header-only" {
			name := "_cpm_" + safePath(s.Owner+"_"+s.Repo)
			fmt.Fprintf(&b, "add_library(%s INTERFACE)\ntarget_include_directories(%s INTERFACE \"${_CPM_ROOT}/%s/include\")\nadd_library(cpm::%s_%s ALIAS %s)\n", name, name, relative, safePath(s.Owner), safePath(s.Repo), name)
		}
	}
	return atomicWrite(filepath.Join(root, ".cpm", "generated", "dependencies.cmake"), []byte(b.String()), 0o644)
}
