package cpm

import (
	"fmt"
	"path/filepath"
	"strings"
)

func (m Manifest) TargetName() string {
	var b strings.Builder
	for _, r := range m.Project.Name {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "app"
	}
	return b.String()
}

func RenderManagedProject(root string, manifest Manifest, lock Lock) error {
	if !manifest.Managed() {
		return fmt.Errorf("%s is not a CPM-managed project", root)
	}
	if err := GenerateCMake(root, lock); err != nil {
		return err
	}
	return atomicWrite(filepath.Join(root, "CMakeLists.txt"), []byte(managedCMake(manifest)), 0o644)
}

func managedCMake(m Manifest) string {
	target := m.TargetName()
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by CPM; edit cpm.toml and use CPM commands instead.\ncmake_minimum_required(VERSION 3.14)\nproject(%s VERSION %s LANGUAGES C CXX)\n\n", target, m.Project.Version)
	fmt.Fprintf(&b, "set(CMAKE_CXX_STANDARD %d)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\nset(CMAKE_CXX_EXTENSIONS OFF)\n\n", m.Build.CPPStandard)
	b.WriteString("include(\"${CMAKE_CURRENT_SOURCE_DIR}/.cpm/generated/dependencies.cmake\")\n\nset(_CPM_SOURCES\n")
	if m.Build.AutoDiscoverSources {
		b.WriteString("  ${CMAKE_CURRENT_SOURCE_DIR}/src/*.c\n  ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cc\n  ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp\n  ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cxx\n")
	}
	for _, source := range m.Build.Sources {
		fmt.Fprintf(&b, "  ${CMAKE_CURRENT_SOURCE_DIR}/%s\n", filepath.ToSlash(source))
	}
	b.WriteString(")\nfile(GLOB_RECURSE _CPM_SOURCES CONFIGURE_DEPENDS ${_CPM_SOURCES})\nlist(REMOVE_DUPLICATES _CPM_SOURCES)\n\n")
	if m.Project.Type == "library" {
		fmt.Fprintf(&b, "add_library(%s STATIC ${_CPM_SOURCES})\ntarget_include_directories(%s PUBLIC \"${CMAKE_CURRENT_SOURCE_DIR}/include\")\n", target, target)
	} else {
		fmt.Fprintf(&b, "add_executable(%s ${_CPM_SOURCES})\n", target)
	}
	if len(m.Build.Links) > 0 {
		fmt.Fprintf(&b, "target_link_libraries(%s PRIVATE\n", target)
		for _, link := range m.Build.Links {
			fmt.Fprintf(&b, "  %s\n", link)
		}
		b.WriteString(")\n")
	}
	b.WriteString("\ninclude(CTest)\nif(BUILD_TESTING)\n")
	if m.Project.Type == "library" {
		fmt.Fprintf(&b, "  add_executable(%s_smoke \"${CMAKE_CURRENT_SOURCE_DIR}/tests/smoke.cpp\")\n  target_link_libraries(%s_smoke PRIVATE %s)\n  add_test(NAME %s_smoke COMMAND %s_smoke)\n", target, target, target, target, target)
	} else {
		fmt.Fprintf(&b, "  add_test(NAME %s_smoke COMMAND %s)\n", target, target)
	}
	b.WriteString("endif()\n")
	return b.String()
}
