package nodus

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func renderDependencies(manifest Manifest) []byte {
	var b strings.Builder
	b.WriteString("# Generated by Nodus from nodus.toml. Do not edit.\ninclude_guard(GLOBAL)\n\n")
	for _, item := range SortedDependencies(manifest) {
		dep := manifest.Dependencies[item.Alias]
		fmt.Fprintf(&b, "CPMAddPackage(\n  NAME %s\n", quoteCMakeIdentifier(item.Alias))
		for _, line := range renderSource(dep) {
			fmt.Fprintf(&b, "  %s\n", line)
		}
		keys := sortedMapKeys(dep.CMake.Arguments)
		for _, key := range keys {
			fmt.Fprintf(&b, "  %s %s\n", key, quoteCMake(dep.CMake.Arguments[key]))
		}
		if len(dep.CMake.Options) > 0 {
			b.WriteString("  OPTIONS\n")
			for _, key := range sortedMapKeys(dep.CMake.Options) {
				fmt.Fprintf(&b, "    %s\n", quoteCMake(key+" "+dep.CMake.Options[key]))
			}
		}
		b.WriteString(")\n\n")
	}
	return []byte(b.String())
}

func renderSource(dep Dependency) []string {
	source := strings.TrimSpace(dep.Source)
	if ownerRepo, ok := hostedRepository(source, "github.com"); ok {
		return appendRef([]string{"GITHUB_REPOSITORY " + quoteCMake(ownerRepo)}, dep.Ref)
	}
	if ownerRepo, ok := hostedRepository(source, "gitlab.com"); ok {
		return appendRef([]string{"GITLAB_REPOSITORY " + quoteCMake(ownerRepo)}, dep.Ref)
	}
	if isLocalSource(source) {
		// dependencies.cmake lives at cmake/nodus. Anchor relative paths at
		// the project root instead of CMake's transient FetchContent build dir.
		if filepath.IsAbs(source) {
			return []string{"SOURCE_DIR " + quoteCMakePath(source)}
		}
		return []string{"SOURCE_DIR " + quoteCMakePath("${CMAKE_CURRENT_LIST_DIR}/../../"+source)}
	}
	if isArchive(source) {
		return []string{"URL " + quoteCMake(source)}
	}
	return appendRef([]string{"GIT_REPOSITORY " + quoteCMake(source)}, dep.Ref)
}

func appendRef(lines []string, ref string) []string {
	if ref != "" {
		return append(lines, "GIT_TAG "+quoteCMake(ref))
	}
	return lines
}

func hostedRepository(source, host string) (string, bool) {
	value := strings.TrimSuffix(strings.TrimSuffix(strings.TrimSpace(source), "/"), ".git")
	if strings.HasPrefix(value, "git@"+host+":") {
		return strings.TrimPrefix(value, "git@"+host+":"), true
	}
	if strings.HasPrefix(value, "ssh://git@"+host+"/") {
		return strings.TrimPrefix(value, "ssh://git@"+host+"/"), true
	}
	value = strings.TrimPrefix(value, "https://")
	value = strings.TrimPrefix(value, "http://")
	if !strings.HasPrefix(value, host+"/") {
		return "", false
	}
	parts := strings.Split(strings.TrimPrefix(value, host+"/"), "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", false
	}
	return strings.Join(parts, "/"), true
}

func isLocalSource(value string) bool {
	return strings.HasPrefix(value, "./") || strings.HasPrefix(value, "../") ||
		strings.HasPrefix(value, `.\`) || strings.HasPrefix(value, `..\`) ||
		filepath.IsAbs(value)
}
func isArchive(value string) bool {
	lower := strings.ToLower(strings.Split(value, "?")[0])
	return strings.HasSuffix(lower, ".zip") || strings.HasSuffix(lower, ".tar") || strings.HasSuffix(lower, ".tar.gz") || strings.HasSuffix(lower, ".tgz")
}
func quoteCMake(value string) string           { return "\"" + strings.ReplaceAll(value, "\"", "\\\"") + "\"" }
func quoteCMakePath(value string) string       { return quoteCMake(strings.ReplaceAll(value, `\`, "/")) }
func quoteCMakeIdentifier(value string) string { return value }
func sortedMapKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func ensureNodusBlock(root string, manifest Manifest) error {
	path := filepath.Join(root, "CMakeLists.txt")
	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		b = []byte(defaultCMake(manifest))
		err = nil
	}
	if err != nil {
		return err
	}
	updated, err := upsertNodusBlock(string(b))
	if err != nil {
		return err
	}
	return atomicWrite(path, []byte(updated), 0o644)
}

func upsertNodusBlock(contents string) (string, error) {
	start, end := strings.Index(contents, managedBlockStart), strings.Index(contents, managedBlockEnd)
	if start >= 0 || end >= 0 {
		if start < 0 || end < 0 || end < start {
			return "", fmt.Errorf("CMakeLists.txt has malformed Nodus managed markers; repair them before continuing")
		}
		end += len(managedBlockEnd)
		prefix := strings.TrimRight(contents[:start], "\n")
		suffix := strings.TrimLeft(contents[end:], "\n")
		updated := prefix + "\n\n" + nodusBlock()
		if suffix != "" {
			updated += "\n" + suffix
		}
		return updated, nil
	}
	lower := strings.ToLower(contents)
	project := strings.Index(lower, "project(")
	if project < 0 {
		return "", fmt.Errorf("CMakeLists.txt has no project(...) call; add one before running nodus init")
	}
	close := strings.Index(contents[project:], ")")
	if close < 0 {
		return "", fmt.Errorf("CMakeLists.txt has an unterminated project(...) call")
	}
	close += project + 1
	return contents[:close] + "\n\n" + nodusBlock() + strings.TrimLeft(contents[close:], "\n"), nil
}

func nodusBlock() string {
	return managedBlockStart + "\n# Managed by Nodus. Edit dependencies with `nodus add` and `nodus remove`.\nset(EXTRACTED_CPM_VERSION \"" + CPMCMakeVersion + "\")\ninclude(\"${CMAKE_CURRENT_LIST_DIR}/cmake/nodus/CPM.cmake\")\nCPMUsePackageLock(\"${CMAKE_CURRENT_LIST_DIR}/cmake/nodus/package-lock.cmake\")\ninclude(\"${CMAKE_CURRENT_LIST_DIR}/cmake/nodus/dependencies.cmake\")\n" + managedBlockEnd + "\n"
}

func defaultCMake(manifest Manifest) string {
	name := targetName(manifest.Project.Name)
	return fmt.Sprintf("cmake_minimum_required(VERSION 3.14)\nproject(%s VERSION %s LANGUAGES C CXX)\n", name, manifest.Project.Version)
}

func targetName(name string) string {
	return strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			return r
		}
		return '_'
	}, name)
}
